name: phi
description: "Phi — flexible workstation for live electronic music performance"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.1
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  yse:
    path: ../dart-yse
  google_fonts: ^6.2.1
  vector_math: ^2.1.4
  macbear_3d:
    git:
      url: https://github.com/yvanvds/macbear_3d.git
      ref: 66b07310b4c135e1d8b842fc046f4a49fd9c3018
  re_editor: ^0.9.0
  re_highlight: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
