sonar.projectKey=yvanvds_phi
sonar.organization=yvanvds
sonar.host.url=https://sonarcloud.io

sonar.projectName=Phi
sonar.projectVersion=0.1.0

sonar.sources=lib
sonar.tests=test,integration_test
sonar.sourceEncoding=UTF-8

sonar.dart.coverage.reportPaths=coverage/lcov.info

sonar.exclusions=**/*.g.dart,**/*.freezed.dart,windows/**,build/**,.dart_tool/**,design system/**
